# Generated by Django 5.2.4 on 2025-07-22 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupdata',
            old_name='password2',
            new_name='password',
        ),
    ]
