# Generated by Django 5.2.5 on 2025-08-20 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Home.signupdata'),
        ),
    ]
