# Generated by Django 5.2.4 on 2025-07-22 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_password2_signupdata_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupdata',
            name='password1',
        ),
    ]
