# Generated by Django 5.2.4 on 2025-07-22 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_remove_signupdata_password1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100, verbose_name='Event Title')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('type', models.CharField(default='Program', max_length=30, verbose_name='Event Type')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('available', models.IntegerField(blank=True, null=True)),
                ('venue', models.CharField(default='TBD', max_length=100)),
                ('Money', models.IntegerField(blank=True, null=True)),
                ('for_class', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
