# Generated by Django 5.2.5 on 2025-08-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_students_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
