# Generated by Django 5.2.4 on 2025-07-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupdata',
            name='organization',
            field=models.CharField(default='Default Org', max_length=100),
        ),
    ]
