# Generated by Django 5.2.4 on 2025-07-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_events_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdata',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
