# Generated by Django 5.2.4 on 2025-08-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_signupdata_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdata',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
