# Generated by Django 5.2.4 on 2025-08-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_signupdata_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdata',
            name='organization',
            field=models.CharField(max_length=100),
        ),
    ]
