# Generated by Django 5.2.4 on 2025-08-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
