# Generated by Django 5.2.4 on 2025-08-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_alter_students_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='faculty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
