# Generated by Django 5.2.4 on 2025-08-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_exceldata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelData',
        ),
    ]
