# Generated by Django 5.2.4 on 2025-08-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_delete_exceldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdata',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
